# =========================
# Namespace
# =========================
apiVersion: v1
kind: Namespace
metadata:
  name: streaming

---
# =========================
# Headless Service - Controller
# =========================
apiVersion: v1
kind: Service
metadata:
  name: kafka-controller
  namespace: streaming
spec:
  clusterIP: None
  selector:
    app: kafka-controller
  ports:
    - name: controller
      port: 9093

---
# =========================
# Headless Service - Broker
# =========================
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: streaming
spec:
  clusterIP: None
  selector:
    app: kafka-broker
  ports:
    - name: broker
      port: 9092

---
# =========================
# StatefulSet - Controller
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-controller
  namespace: streaming
spec:
  serviceName: kafka-controller
  replicas: 1
  selector:
    matchLabels:
      app: kafka-controller
  template:
    metadata:
      labels:
        app: kafka-controller
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6.0
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "kraft-cluster-01"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LISTENERS
              value: "CONTROLLER://:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-controller-0.kafka-controller.streaming.svc.cluster.local:9093"
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: kafka-storage
        resources:
          requests:
            storage: 10Gi

---
# =========================
# StatefulSet - Broker
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: streaming
spec:
  serviceName: kafka-broker
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "kraft-cluster-01"
            - name: KAFKA_CFG_NODE_ID
              value: "2"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-0.kafka-broker.streaming.svc.cluster.local:9092"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-controller-0.kafka-controller.streaming.svc.cluster.local:9093"
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: kafka-storage
        resources:
          requests:
            storage: 10Gi
